name: ReportCard

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CheckReportCard:
  steps:
    push: name: Go report card
    uses: creekorful/goreportcard-action@v1.0
